# -*- coding: utf-8 -*-
"""mtcars.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hmSUpbr13Nqxt6ex2z4VpsSTkqZ9II21

EDA on MTCARS using R

by Yoihen Elangbam
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

# Commented out IPython magic to ensure Python compatibility.
# %%R
# #install
# install.packages("corrplot")
# install.packages("dplyr")
# install.packages("ggplot2")
# #Load Required Libraries
# library(ggplot2)
# library(dplyr)
# library(corrplot)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Load Dataset
# data <- mtcars

# Commented out IPython magic to ensure Python compatibility.
# %%R
# head(data)
# str(data)       # Check the structure of the dataset

# Commented out IPython magic to ensure Python compatibility.
# %%R
# summary(data)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Check for Missing Values
# sum(is.na(data))

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Histogram of Miles per Gallon (mpg)
# ggplot(data, aes(x = mpg)) +
#   geom_histogram(binwidth = 2, fill = "magenta", color = "black") +
#   theme_minimal() +
#   labs(title = "Distribution of Miles Per Gallon (mpg)", x = "Miles Per Gallon", y = "Frequency")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Scatter Plot between Horsepower (hp) and Miles per Gallon (mpg)
# ggplot(data, aes(x = hp, y = mpg)) +
#   geom_point(color = "pink") +
#   theme_minimal() +
#   labs(title = "Scatter Plot: Horsepower vs Miles per Gallon", x = "Horsepower", y = "Miles per Gallon")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Correlation Matrix for mtcars Dataset
# cor_matrix <- cor(data %>% select_if(is.numeric))
# print(cor_matrix)
# corrplot(cor_matrix, method = "circle",col = colorRampPalette(c("pink", "white", "skyblue"))(200))

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Boxplot of mpg by cylinder (cyl)
# ggplot(mtcars, aes(x = factor(cyl), y = mpg, fill = factor(cyl))) +
#   geom_boxplot() +
#   labs(title = "MPG by Cylinder",
#        x = "Number of Cylinders",
#        y = "Miles per Gallon") +
#   theme_minimal()

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Density plot of mpg
# ggplot(mtcars, aes(x = mpg)) +
#   geom_density(fill = "skyblue", alpha = 0.7) +
#   labs(title = "Density of MPG",
#        x = "Miles per Gallon",
#        y = "Density") +
#   theme_minimal()

